### ISSUE TITLE
.env file not properly populated.

### ISSUE THREAD

**Issue by paulioceano** [auth0-community/auth0-hapi-api-samples#13]
After check that I'm logged in, when the sample is downloaded, the field ´AUTH0_DOMAIN´ is not pre-populated.

![screenshot_1](https://user-images.githubusercontent.com/15818783/44685922-acd03d00-aa1a-11e8-8a39-9aa59831b7fe.png)

**Comment by paulioceano** [comment]
The link is the QS for backend Hapi: https://auth0.com/docs/quickstart/backend/hapi.

Steps to reproduce this:

- Go to the QS link (https://auth0.com/docs/quickstart/backend/hapi)
- Click in Login in the topbar of the page.
- Once you are logged, Click in the "Download Sample" button.
- In my case, the download link was:
https://auth0.com/docs/package/v2?branch=master&org=auth0-community&repo=auth0-hapi-api-samples&path=01-Authenticate-RS256&client_id=&api_id=api.quickstart.test

**Comment by jerdog** [comment]
Ok - so the .env file is there - MacOS doesn't show `.` files in Finder 🤦‍♂️ 

Doing some checking internally to see what can be done. You can of course edit them with the information

**Comment by paulioceano** [comment]
Yes, after editing manually the .env file, the sample run without any problem.

However, this same issue happens with the falcor sample (https://auth0.com/docs/quickstart/backend/falcor), but other samples have both ´AUTH0_IDENTIFIER´ and ´AUTH0_DOMAIN´ filled properly.

**Comment by albertoperdomo** [comment]
Hello @paulioceano,

we had some issues with the logic that injects the env vars, which were fixed yesterday.
Can you please test again and update this issue according to the result (update with a comment, close if appropriate) ?

Thanks!

**Comment by paulioceano** [comment]
Hello @albertoperdomo.

Already test it again and the .env file is correct now.

Closing issue.
