### ISSUE TITLE
How to pass scope to the sample server ?

### ISSUE THREAD

**Issue by datauduong** [auth0-community/auth0-hapi-api-samples#4]
Hi,

I have downloaded the sample: 01-Authenticate-RS256.

I am using the sample from Auth0 to connect to 
http://localhost:3001/Api/Private
with the Access Token already embed.

I get an error message:
{"statusCode":401,"error":"Unauthorized","message":"Invalid token","attributes":{"error":"Invalid token"}}

I've fixed the error: Unauthorized, it was due to the sample server code download does not populate the AUTH0_AUDIENCE={AUDIENCE}

Auth0 now use scope, but the sample to call API from Auth0 only Add Authorization header with the bearer token only.
**{"statusCode":403,"error":"Forbidden","message":"Insufficient scope"}**

How do you pass the access_token, including scope ?

Sample of Node.js or C# would be very helpful.

Thank you.

**Comment by chenkie** [comment]
You need to request any desired `scope`s in the initial authentication transaction you make. So if you are logging a user into Auth0 with auth0-js, you can add the `read:messages` scope (required for this sample) into the `WebAuth` call.

Have a look at this doc for more: https://auth0.com/docs/quickstart/spa/vanillajs/03-calling-an-api
